config/routes.rb
SimpleAccounting::Application.routes.draw do
  resources :http_requests

  resources :bank_books, shallow: true do 
    resources :operations
  end

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  resources :users
  resources :activities
  get 'home/geo'
  match 'data' => 'home#fake', via: :get
end

app/models/http_request.rb
class HttpRequest < ActiveRecord::Base
end

app/controllers/http_requests_controller.rb
class HttpRequestsController < ApplicationController
  before_action :set_http_request, only: [:show, :edit, :update, :destroy]

  # GET /http_requests
  # GET /http_requests.json
  def index
    @http_requests = HttpRequest.order("created_at DESC").page(params[:page]).per(10)
  end

  # GET /http_requests/1
  # GET /http_requests/1.json
  def show
  end

  # GET /http_requests/new
  def new
    @http_request = HttpRequest.new
  end

  # GET /http_requests/1/edit
  def edit
  end

  # POST /http_requests
  # POST /http_requests.json
  def create
    @http_request = HttpRequest.new(http_request_params)

    respond_to do |format|
      if @http_request.save
        format.html { redirect_to @http_request, notice: 'Http request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @http_request }
      else
        format.html { render action: 'new' }
        format.json { render json: @http_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /http_requests/1
  # PATCH/PUT /http_requests/1.json
  def update
    respond_to do |format|
      if @http_request.update(http_request_params)
        format.html { redirect_to @http_request, notice: 'Http request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @http_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /http_requests/1
  # DELETE /http_requests/1.json
  def destroy
    @http_request.destroy
    respond_to do |format|
      format.html { redirect_to http_requests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_http_request
      @http_request = HttpRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def http_request_params
      params.require(:http_request).permit(:method, :parameters, :ip_address)
    end
end

app/helpers/http_requests_helper.rb
module HttpRequestsHelper
end

app/views/http_requests/_form.html.erb
<%= simple_form_for(@http_request) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :method %>
    <%= f.input :parameters %>
    <%= f.input :ip_address %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/http_requests/edit.html.erb
<h1>Editing http_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @http_request %> |
<%= link_to 'Back', http_requests_path %>

app/views/http_requests/index.html.erb
<h1>Сетевые запросы к системе</h1>

<%= paginate @http_requests %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Дата</th>
      <th>Parameters</th>
      <th>IP</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @http_requests.each do |http_request| %>
      <tr>
        <td><%= http_request.created_at.strftime("%c") %></td>
        <td><%= http_request.parameters %></td>
        <td><%= http_request.ip_address %></td>
        <td><%= link_to 'Show', http_request %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @http_requests %>

<br>

<%= link_to 'New Http request', new_http_request_path %>

app/views/http_requests/new.html.erb
<h1>New http_request</h1>

<%= render 'form' %>

<%= link_to 'Back', http_requests_path %>

app/views/http_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Method:</strong>
  <%= @http_request.method %>
</p>

<p>
  <strong>Parameters:</strong>
  <%= @http_request.parameters %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @http_request.ip_address %>
</p>

<%= link_to 'Edit', edit_http_request_path(@http_request) %> |
<%= link_to 'Back', http_requests_path %>