config/routes.rb
SimpleAccounting::Application.routes.draw do
  resources :http_requests

  resources :bank_books, shallow: true do 
    resources :operations
  end

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  resources :users
  resources :activities
  get 'home/geo'
  match 'data' => 'home#fake', via: :get
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :bank_books
  validate :all_password_must_be_different

  def all_password_must_be_different
    if self.fake_password == self.alert_password
      errors.add :password_diff, "Пароли должны отличаться"
    end
  end
  def to_s
    "#{name} - #{roles.first.to_s}"
  end

  def check_type_of_login input_password
    case input_password
      when self.fake_password
        puts "FAKE PASSWORD"
        self.create_activity :fake_password, owner: self
        return false
      else
        return true
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find params[:id]
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user].permit!)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<%= content_for :side_menu do %>
  <% if current_user.has_role? :admin %>
    <li>
      <%= link_to "Добавить пользователя", new_user_invitation_path %>
    </li>
  <% end %>
<% end %>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>ФИО</th>
      <th>Почта</th>
      <th>Зарегистрирован</th>
      <th>Роль</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini btn-danger') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<h3>Пользователь</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<% if current_user.has_role? :admin %>
  <p>IP актуальной сессии: <%= @user.current_sign_in_ip %></p>
  <p>Последняя сессия: <b>Дата</b> <%= @user.last_sign_in_at %> <b>IP:</b> <%= @user.last_sign_in_ip %></p>
<% end %>
  <% if can?(:manage, @user) %>
    <%= link_to "Изменить", edit_registration_path(@user), class: "btn" %>
  <% end %>
  <% if current_user.has_role? :admin %>
  <% end %>