config/routes.rb
SimpleAccounting::Application.routes.draw do
  resources :http_requests

  resources :bank_books, shallow: true do 
    resources :operations
  end

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  resources :users
  resources :activities
  get 'home/geo'
  match 'data' => 'home#fake', via: :get
end

app/models/bank_book.rb
class BankBook < ActiveRecord::Base
  self.primary_key = :id
  has_and_belongs_to_many :users
  has_many :operations

  validates :id, presence: true

  def to_s
    "#{name} - #{id}"
  end
end

app/controllers/bank_books_controller.rb
class BankBooksController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_bank_book, only: [:show, :edit, :update, :destroy]

  # GET /bank_books
  # GET /bank_books.json
  def index
    @bank_books = BankBook.all
  end

  # GET /bank_books/1
  # GET /bank_books/1.json
  def show
  end

  # GET /bank_books/new
  def new
    @bank_book = BankBook.new
  end

  # GET /bank_books/1/edit
  def edit
  end

  # POST /bank_books
  # POST /bank_books.json
  def create
    @bank_book = BankBook.new(bank_book_params)

    respond_to do |format|
      if @bank_book.save
        format.html { redirect_to @bank_book, notice: 'Bank book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bank_book }
      else
        format.html { render action: 'new' }
        format.json { render json: @bank_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_books/1
  # PATCH/PUT /bank_books/1.json
  def update
    respond_to do |format|
      if @bank_book.update(bank_book_params)
        format.html { redirect_to @bank_book, notice: 'Bank book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bank_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_books/1
  # DELETE /bank_books/1.json
  def destroy
    @bank_book.destroy
    respond_to do |format|
      format.html { redirect_to bank_books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_book
      @bank_book = BankBook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_book_params
      params.require(:bank_book).permit(:id, :name, :bank_account, :total, :saldo)
    end
end

app/helpers/bank_books_helper.rb
module BankBooksHelper
end

app/views/bank_books/_account_table.html.erb
<h4>Приход</h4>
<table class="table datatable">
  <thead>
    <th>#</th>
    <th>Дата</th>
    <th>От кого</th>
    <th>Кому</th>
    <th>Сумма</th>
    <th>Тип</th>
    <th>Назначение</th>
    <th>Приход/Расход</th>
    <th>Ввёл</th>
    <th></th>
    <th></th>
  </thead>
  <tbody>
    <% records.each do |r| %>
      <tr>
        <td><%= link_to r.id, r %></td>
        <td><%= r.o_date %></td>
        <td><%= r.from.try :name %></td>
        <td><%= r.to_user.try :name %></td>
        <td><%= r.amount %></td>
        <td><%= r.money_type_operation.name %></td>
        <td><%= r.description %></td>
        <td><%= r.io_type_operation.name %></td>
        <td><%= r.user.try(:name) || r.user.email %></td>
        <td><%=link_to "Изменить", edit_operation_path(r), class: "btn btn-primary" %></td>
        <td><%=link_to "Удалить", operation_path(r), method: :delete, confirm: "Вы уверены?", class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bank_books/_form.html.erb
<%= simple_form_for(@bank_book) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :id %>
    <%= f.input :name %>
    <%= f.input :bank_account %>
    <%= f.input :amount %>
    <%= f.input :saldo %>
    <%= f.association :users, label: "Имеют доступ",as: :check_boxes,:label_method => lambda { |owner| "#{owner.name} | #{owner.roles.map {|r| r.name }}" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit,  "Готово", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/bank_books/edit.html.erb
<h1>Editing bank_book</h1>

<%= render 'form' %>

<%= link_to 'Show', @bank_book %> |
<%= link_to 'Back', bank_books_path %>

app/views/bank_books/index.html.erb
<%= content_for :side_menu do %>
  <li><%= link_to "Добавить счёт", new_bank_book_path %></li>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th>№ Счёта</th>
      <th>Наименование</th>
      <th>Прикрепленные банковские счета</th>
      <th>Сумма</th>
      <th>Дневное сальдо</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bank_books.each do |bank_book| %>
        <% if can? :manage, bank_book %>
        <tr>
          <td><%= bank_book.id %></td>
          <td><%= bank_book.name %></td>
          <td><%= bank_book.bank_account %></td>
          <td><%= bank_book.amount %></td>
          <td><%= bank_book.saldo %></td>
          <td><%= link_to 'Открыть', bank_book, class: "btn btn-primary" %></td>
          <td><%= link_to 'Редактировать', edit_bank_book_path(bank_book), class: "btn" %></td>
          <td><%= link_to 'Удалить', bank_book, method: :delete, data: { confirm: 'Вы уверены?' }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

app/views/bank_books/new.html.erb
<h1>Новый лицевой счёт</h1>

<%= render 'form' %>

<%= link_to 'Back', bank_books_path %>

app/views/bank_books/show.html.erb
<%= content_for :side_menu do %>

  <li><%= link_to "Добавить операцию", new_bank_book_operation_path(@bank_book)  %></li>
  <li><%= link_to 'Редактировать', edit_bank_book_path(@bank_book) %></li>
<% end %>



<div class="row">

    <blockquote class="pull-right">
      <p>
        <strong>Лицевой счёт:</strong>
         <%= @bank_book.name %> - <%= @bank_book.id %>
      </p>
      <p>
        <strong>Состояние на <%= @bank_book.updated_at.strftime("%Y-%m-%d %H:%M") %></strong>
      <p>
        <strong>Сумма:</strong>
        <%= number_to_currency @bank_book.amount %>
      </p>

      <p>
        <strong>Сальдо:</strong>
        <%= number_to_currency @bank_book.saldo %>
      </p> 
    </blockquote>
</div>
<div class="row">

  <div class="span12">
    <%= render partial: 'account_table', locals: {records: @bank_book.operations} %>
  </div>

</div>