config/routes.rb
SimpleAccounting::Application.routes.draw do
  resources :http_requests

  resources :bank_books, shallow: true do 
    resources :operations
  end

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  resources :users
  resources :activities
  get 'home/geo'
  match 'data' => 'home#fake', via: :get
end

app/models/operation.rb
class Operation < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }
  belongs_to :user
  belongs_to :from, class_name: "User"
  belongs_to :to_user, class_name: "User"
  belongs_to :money_type_operation
  belongs_to :io_type_operation
  belongs_to :bank_book

  after_create :windraw_amount_from_bank_book

  def to_s
    "#{io_type_operation.name} #{amount}"
  end

  private

  def windraw_amount_from_bank_book
    if io_type_operation.name == "Приход"
      bank_book.decrement! :amount, self.amount
    elsif io_type_operation.name == "Расход"
      bank_book.increment! :amount, self.amount
    else
      raise Exception.new "Unsupported operation"
    end
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :find_bank_account, only: [:index, :new, :create]
  before_action :set_operation, only: [:show, :edit, :update, :destroy]
  
  # GET /operations
  # GET /operations.json
  def index
    @operations = @bank_book.operations
  end

  # GET /operations/1
  # GET /operations/1.json
  def show
    @operation  = Operation.find params[:id]
  end

  # GET /operations/new
  def new
    @operation = @bank_book.operations.build
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations
  # POST /operations.json
  def create
    @operation = Operation.new(operation_params)
    @operation.user = current_user
    @bank_book.operations << @operation
    respond_to do |format|
      if @bank_book.save
        format.html { redirect_to @bank_book, notice: 'Operation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @operation }
      else
        format.html { render action: 'new' }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1
  # PATCH/PUT /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to @operation, notice: 'Operation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1
  # DELETE /operations/1.json
  def destroy
    @operation.destroy
    respond_to do |format|
      format.html { redirect_to bank_books_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operation_params
      params[:operation].permit!
    end

    def find_bank_account
      @bank_book = BankBook.find params[:bank_book_id]
    end 
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.erb
<%= simple_form_for([@bank_book, @operation]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div id="datetimepicker1" class="input-append date">
      <input name="operation[o_date]" data-format="dd/MM/yyyy hh:mm:ss" type="text"></input>
      <span class="add-on">
        <i data-time-icon="icon-time" data-date-icon="icon-calendar">
        </i>
      </span>
    </div>
    <script type="text/javascript">

</script>
    <%= f.association :from, label: "От кого" %>
    <%= f.association :to_user, label: "Кому" %>
    <%= f.association :money_type_operation, label: "Тип расчёта" %>
    <%= f.association :io_type_operation, label: "Тип операции" %>
    <%= f.input :description, label: "Назначение" %>

    <%= f.input :amount, label: "Сумма" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Готово" %>
  </div>
<% end %>

app/views/operations/edit.html.erb
<h1>Редактирование операции</h1>

<%= render 'form' %>

<%= link_to 'Назад', @bank_book %>

app/views/operations/index.html.erb
<h1>Listing operations</h1>

<table class='datatable'>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @operations.each do |operation| %>
      <tr>
        <td><%= link_to 'Show', operation %></td>
        <td><%= link_to 'Edit', edit_operation_path(operation) %></td>
        <td><%= link_to 'Destroy', operation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Operation', new_operation_path %>

app/views/operations/new.html.erb
<h2>Добавить операцию для счёта <%= @bank_book %></h2>

<%= render 'form' %>

app/views/operations/show.html.erb
<%= link_to 'Edit', edit_operation_path(@operation) %> |